uvmadmin_v4/core/urls.py
from django.urls import path
from .views import home

core_patterns = ([
    path('', home.as_view(), name='home'),  
], 'core')

uvmadmin_v4/gallery/urls.py
from django.urls import path

from gallery.views import (AlbumView, AlbumList, 
                           AlbumCreate, AlbumDelete, AlbumUpdate)

app_name = 'gallery'
urlpatterns = [
    path('', AlbumList.as_view(), name='album_list'),
    path('album/<int:pk>/<slug>/', AlbumView.as_view(), name='album_detail'),
    path('borrar/<int:pk>/', AlbumDelete.as_view(), name='album_delete'),
    path('crear/', AlbumCreate.as_view(), name='album_create'),
    path('editar/<int:pk>/', AlbumUpdate.as_view(), name='album_update'),
]

uvmadmin_v4/noticias/urls.py
from django.urls import path
from .views import NoticiaListView, NoticiaDetailView, NoticiaCreate, NoticiaUpdate, NoticiaDelete

noticias_patterns = ([
    path('', NoticiaListView.as_view(), name='noticias'),
    path('<int:pk>/<slug:slug>/', NoticiaDetailView.as_view(), name='noticia'),
    path('crear/', NoticiaCreate.as_view(), name='crear'),
    path('editar/<int:pk>/', NoticiaUpdate.as_view(), name='editar'),
    path('borrar/<int:pk>/', NoticiaDelete.as_view(), name='borrar'),
], 'noticias')

uvmadmin_v4/uvmadmin/urls.py
from django.contrib import admin
from django.urls import path, include
# URLs de las App Propias
from core.urls import core_patterns       
from noticias.urls import noticias_patterns     
from alumnos.urls import alumnos_patterns  
from ponentes.urls import ponentes_patterns
from materias.urls import materias_patterns
from matriculas.urls import matriculas_patterns
from pages.urls import pages_patterns
from universidad.urls import universidad_patterns
      
# Para poder ver imágenes en desarrollo (fichero static). Ver abajo del todo
from django.conf import settings

urlpatterns = [
    # Paths de las App propias
    path('', include(core_patterns)),
    path('noticias/', include(noticias_patterns)),
    path('alumnos/', include(alumnos_patterns)),
    path('materias/', include(materias_patterns)),
    path('ponentes/', include(ponentes_patterns)),
    path('matriculas/', include(matriculas_patterns)),
    path('paginas/', include(pages_patterns)),
    path('universidad/', include(universidad_patterns)),
    # Paths de terceros
    path('galeria/', include('gallery.urls')),
    # Paths del admin
    path('admin/', admin.site.urls),
    # Paths de Auth (Autenticación)
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('registration.urls')),        # Aumentamos las listas de posibles paths de accounts
]

# Para poder ver imágenes en desarrollo (fichero static)
if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

uvmadmin_v4/noticias/models.py
from django.db import models                    # Para trabajar con modelos
from django.utils.timezone import now           # Para coger la fecha actual
from django.contrib.auth.models import User     # Para relacionar con Users de Django
from gallery.models import Album                # Para enlazar la Noticia con un álbum de fotos
from ckeditor.fields import RichTextField       # Para incluir el editor de texto CKEditor

DEFAULT_USER_ID = 2
class Noticia(models.Model):
    title = models.CharField(verbose_name="Título", max_length=200)
    subject = models.CharField(verbose_name="Entradilla", max_length=200, default="")
    content = RichTextField(verbose_name="Contenido")
    image = models.ImageField(upload_to='noticias', null=True, blank=True)
    published = models.DateTimeField(verbose_name="Fecha de publicación", default=now)
    author = models.ForeignKey(User, verbose_name="Autor", default=DEFAULT_USER_ID,  on_delete=models.CASCADE) 
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edición")
    galeria = models.ForeignKey(Album, verbose_name="Galeria", null=True, blank=True, on_delete=models.SET_NULL) 
    fichero = models.FileField(upload_to='noticias', null=True, blank=True)

    class Meta:
        verbose_name = "noticia"
        verbose_name_plural = "noticias"
        ordering = ['-created', 'title']

    def __str__(self):
        return self.title

    

uvmadmin_v4/noticias/forms.py
from django import forms
from .models import Noticia

class NoticiaForm(forms.ModelForm):

    class Meta:
        model = Noticia
        fields = ['title', 'subject', 'content', 'image', 'published', 'author', 'galeria', 'fichero']
        widgets = {
			'title': forms.TextInput(attrs={'class': 'form-control input-lg mt-2 mb-2',
                'placeholder': 'Título...', 'required': True
			}),
			'subject': forms.TextInput(attrs={'class': 'form-control input-lg mb-2',
				'placeholder': 'Entradilla...', 'required': True
			}),
			'content': forms.Textarea(attrs={'class': 'form-control input-lg mb-2',
                'required': True
			}),
			'image': forms.ClearableFileInput(attrs={'class': 'form-control-file mb-2'}),
			'published': forms.DateTimeInput(attrs={'class': 'form-control input-lg mb-2'}),
			'author': forms.NumberInput(attrs={'class': 'form-control input-lg mb-2'}),
		    'galeria': forms.Select(attrs={'class': 'form-control mb-2'}),
			'fichero': forms.ClearableFileInput(attrs={'class': 'form-control-file mb-2'}),
        }
        labels = {
            'title':'', 'subject':'', 'content': '', 'image':'', 
            'published':'Fecha de Publicación', 'galeria':'Galería de Fotos'
        }

uvmadmin_v4/noticias/views.py
# Para manejar las vistas genéricas de Django
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
# Para controlar el acceso de usuarios a las vistas
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.urls import reverse, reverse_lazy
# Importamos los modelos y los formularios de la ap
from .models import Noticia
from .forms import NoticiaForm


#============= Mostrar un PDF ==============#
def pdfView(request):
    image_data = open('', 'rb').read()
    return HttpResponse(image_data, mimetype='application/pdf')


#============= Listado de Noticias ==============#
@method_decorator(login_required, name='dispatch')
class NoticiaListView(ListView):
    model = Noticia

#============ Detalle de una noticia =============#
@method_decorator(login_required, name='dispatch')
class NoticiaDetailView(DetailView):
    model = Noticia
 
#============ Crear una nueva noticia =============#
@method_decorator(login_required, name='dispatch')
class NoticiaCreate(CreateView):
    model = Noticia
    form_class = NoticiaForm
    success_url = reverse_lazy('noticias:noticias')
 
#============ Actualizar nueva noticia =============#
@method_decorator(login_required, name='dispatch')
class NoticiaUpdate(UpdateView):
    model = Noticia
    form_class = NoticiaForm
    template_name_suffix = '_update_form'

    def get_success_url(self):
        return reverse_lazy('noticias:editar', args=[self.object.id]) + '?ok'

#============ Eliminar nueva noticia =============#
@method_decorator(login_required, name='dispatch')
class NoticiaDelete(DeleteView):
    model = Noticia
    success_url = reverse_lazy('noticias:noticias')

uvmadmin_v4/noticias/templates/noticias/noticia_confirm_delete.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Eliminar noticia{% endblock %}

{% block content %}

    <!-- BREADCRUMB -->
    <div class="row">
        <div class="col-xl-12">
            <div class="breadcrumb-holder">
                <h1 class="main-title float-left">Noticias</h1>
                <ol class="breadcrumb float-right">
                    <li class="breadcrumb-item">Inicio</li>
                    <li class="breadcrumb-item">Noticias</li>
                    <li class="breadcrumb-item active">Eliminar</li>
                </ol>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>

    <!-- PANEL DE LA NOTICIA -->
    <div class="card">

      <!-- MENÚ DE NOTICIAS -->
      <h5 class="card-header text-white bg-dark">  
        {% if request.user.is_active %}
          {% include 'noticias/includes/_menu.html'%}
        {% endif %}
      </h5>

      <!-- DETALLE DE LA NOTICIA --> 
      <div class="card-body">
          <form action="" method="post">{% csrf_token %}
            <h5 class="card-title text-center mt-5 mb-5">
              ¿Está seguro de querer borrar la noticia: <b>"{{ object }}"</b>?
            </h5>
            <input type="submit" class="btn btn-danger btn-block" value="Sí, borrar la noticia" />
            <a class="btn btn-secondary btn-block" href="{% url 'noticias:noticias' %}">Cancelar</a>
          </form>

      </div>
    </div>

{% endblock content %}

uvmadmin_v4/noticias/templates/noticias/noticia_detail.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}{{noticia.title}}{% endblock %}

{% block libreriasCSS %}
{% endblock libreriasCSS %}

{% block content %}

    <!-- BREADCRUMB -->
    <div class="row">
        <div class="col-xl-12">
            <div class="breadcrumb-holder">
                <h1 class="main-title float-left">Noticias</h1>
                <ol class="breadcrumb float-right">
                    <li class="breadcrumb-item">Inicio</li>
                    <li class="breadcrumb-item">Noticias</li>
                    <li class="breadcrumb-item active">Detalle</li>
                </ol>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>

    <!-- PANEL DE LA NOTICIA -->
    <div class="card">

        <!-- MENÚ DE NOTICIAS -->
        <h5 class="card-header text-white bg-dark">  
          {% if request.user.is_active %}
            {% include 'noticias/includes/_menu.html'%}
          {% endif %}
        </h5>

        <!-- DETALLE DE LA NOTICIA --> 
        <div class="card-body"> 
            <h5 class="card-title"></h5>
            
            <ul class="nav nav-tabs" id="myTab" role="tablist">
                <li class="nav-item">
                  <a class="nav-link active" data-toggle="tab" href="#tabDetalle" role="tab" aria-controls="home" aria-selected="true">
                    DETALLE
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" id="profile-tab" data-toggle="tab" href="#tabGaleria" role="tab" aria-controls="profile" aria-selected="false">
                    GALERÍA DE FOTOS
                  </a>
                </li>
            </ul>
            
            <!-- Contenido de los TABS -->
            <div class="tab-content" id="myTabContent">

                <!-- Detalle de la Noticia -->
                <div class="tab-pane fade show active" id="tabDetalle" role="tabpanel">
                  <h2 class="section-heading mb-4 mt-4">{{noticia.title}}</h2>
                  <h3 class="section-heading mb-4">{{noticia.subject}}</h3>

                  {% if noticia.image %}
                    <img src="{{noticia.image.url}}" class="img-fluid mt-2">                  
                  {% else %}
                    <img src="{% static 'noticias/img/no-image.png' %}" class="img-fluid mt-2">
                  {% endif %}
                  <hr>

                  {{noticia.content|safe}}

                  {% if noticia.fichero %}
                    <a class="btn btn-info" href="{{noticia.fichero.url}}" target="_blank" role="button">
                      <i class="fas fa-file-pdf"></i> Documento Adjunto
                    </a>
                  {% endif %}

                </div>

                <!-- Galería de Fotos -->
                <div class="tab-pane fade" id="tabGaleria" role="tabpanel">
                  <!-- Galería de Fotos -->
                  {% if noticia.galeria %}
                    <h5 class="card-title mt-4"><strong>Galería:</strong>{{noticia.galeria}}</h5>
                    <div class="card-columns">
                        {% for imagen in noticia.galeria.images.all %}
                            <div class="card">
                              <img class="card-img-top" src="{{imagen.data.url}}">
                            </div>
                        {% endfor %}
                    </div>
                  {% endif %}
                </div>

            </div>
            <!-- FIN TABS -->
        </div>
    </div>

{% endblock content %}


{% block extrascripts %} 
{% endblock extrascripts %}

uvmadmin_v4/noticias/templates/noticias/noticia_form.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Nueva noticia{% endblock title %}

{% block libreriasCSS %} {% endblock libreriasCSS %}

{% block libreriasJS %} 
	<script src="{% static 'core/terceros/jquery/jquery.min.js' %}"></script>
	<script src="{% static 'core/terceros/bootstrap/bootstrap.min.js' %}"></script>
{% endblock %}


{% block content %}

    <!-- BREADCRUMB -->
    <div class="row">
        <div class="col-xl-12">
            <div class="breadcrumb-holder">
                <h1 class="main-title float-left">Noticias</h1>
                <ol class="breadcrumb float-right">
                    <li class="breadcrumb-item">Inicio</li>
                    <li class="breadcrumb-item">Noticias</li>
                    <li class="breadcrumb-item active">Nueva</li>
                </ol>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>

    <!-- PANEL DE LA NOTICIA -->
    <div class="card">

      <!-- MENÚ DE NOTICIAS -->
      <h5 class="card-header text-white bg-dark">  
        {% if request.user.is_active %}
          {% include 'noticias/includes/_menu.html'%}
        {% endif %}
      </h5>

      <!-- DETALLE DE LA NOTICIA --> 
      <div class="card-body">
          <h5 class="card-title"></h5>

          <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
              <div class="row mt-3">
                <!-- IMÁGEN Y BOTONES DEL FORMULARIO -->
                <div class="col-md-2">
                  <div class="row">
                    <input type="submit" class="btn btn-primary btn-block" value="Crear noticia" />
                  </div>
                  <div class="row mt-2">
                    <a class="btn btn-secondary btn-block" href="{% url 'noticias:noticias' %}">Cancelar</a>
                  </div>
                </div>

                <!-- DETALLE DE LA NOTICIA -->
                <div class="col-md-10">  
                  <!-- Usuario activo -->
                  <input type="hidden" id="{{form.author.name}}" name="{{form.author.name}}" value="{{request.user.id}}">             
                  <!-- Imagen de la noticia -->                      
                  <div class="custom-file">                      
                    <input type="file" class="custom-file-input mb-2" accept=".jpg,.gif,.png" 
                            id="{{form.image.name}}" name="{{form.image.name}}">
                    <label class="custom-file-label" for="{{form.image.name}}">Seleccione Imágen de portada...</label>
                  </div>

                  {{ form.title }}
                  {{ form.subject }}
                  {{ form.content }}

                  <div class="form-row">
                    <div class="form-group col-md-4">
                      {{ form.galeria }}
                    </div>
                    <div class="form-group col-md-4">
                      <div class="custom-file">
                        <input type="file" class="custom-file-input" accept=".pdf" id="{{form.fichero.name}}" name="{{form.fichero.name}}" placeholder="{{form.fichero.value}}">
                        <label class="custom-file-label" for="{{form.fichero.name}}">Seleccione Documento Adjunto...</label>
                      </div>        
                    </div>
                    <div class="form-group col-md-4">
                      {{ form.published }}
                    </div>
                  </div>

                </div>              
              </div>
          </form>

      </div>
    </div>

{% endblock content %}

{% block extrascripts %} 
  <script>
    $(".custom-file-input").on("change", function() {
      var fileName = $(this).val().split("\\").pop();
      $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
    });
  </script>
{% endblock extrascripts %}

uvmadmin_v4/noticias/templates/noticias/noticia_list.html
{% extends 'core/base.html' %}          <!-- Cargamos el código html común -->
{% load static %}                       <!-- Cargamos los ficheros estáticos -->

{% block title %}Noticias{% endblock title %}

<!-- Librerías CSS - Específicas para esta página -->
{% block libreriasCSS %}  
    <link rel="stylesheet" href="{% static 'core/terceros/datatable/dataTables.bootstrap4.min.css' %}">
{% endblock libreriasCSS %}

<!-- Contenido principal -->
{% block content %}
    
    <!-- BREADCRUMB -->
    <div class="row">
        <div class="col-xl-12">
            <div class="breadcrumb-holder">
                <h1 class="main-title float-left">Noticias</h1>
                <ol class="breadcrumb float-right">
                    <li class="breadcrumb-item">Inicio</li>
                    <li class="breadcrumb-item">Noticias</li>
                    <li class="breadcrumb-item active">Listado</li>
                </ol>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>

    <!-- LISTADO -->
    <div class="card">
        <h5 class="card-header text-white bg-dark">  
            <a href="{% url 'noticias:crear' %}" class="btn btn-primary" role="button">
                Nueva Noticia 
                <span class="fas fa-plus-circle"></span>
            </a> 
        </h5>

        <div class="card-body">
            <h5 class="card-title"></h5>
            <p class="card-text">
                <table id="iddatatable" class="table table-hover table-condensed table-bordered">
                    <thead style="background-color: #005b9f; color: white; font-weight: bold; ">
                    <tr>
                        <th>Título</th>
                        <th>Entradilla</th>
                        <th>Creada</th>
                        <th>Publicada</th>
                        <th>Borrar</th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for noticia in noticia_list %}
                            <tr>
                                <td><a href="{% url 'noticias:noticia' noticia.id noticia.title|slugify %}">{{noticia.title}}</a></td>
                                <td>{{noticia.subject}}</td>
                                <td>{{noticia.created|date:'d/m/Y'}}</td>                                
                                <td>{{noticia.published|date:'d/m/Y'}}</td>                                
                                <td width="5%">
                                  <a href="{% url 'noticias:borrar' noticia.id %}" id="delNoticia" name="delNoticia" class="btn btn-outline-danger btn-sm">
                                    <i class="fas fa-trash-alt fa-xs"></i>
                                  </a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                    <tfoot style="background-color: #373737; color: white; font-weight: bold;">
                        <th>Título</th>
                        <th>Entradilla</th>
                        <th>Creada</th>
                        <th>Publicada</th>
                        <th>Borrar</th>
                    </tfoot>
                </table> 
            </p>            
        </div>
    </div>

    
    <!-- FIN PANEL LISTADO DE NOTICIAS -->


{% endblock content %}

<!-- Librerías JS - Específicas para esta página -->
{% block extrascripts %}
    <script src="{% static 'core/terceros/datatable/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'core/terceros/datatable/dataTables.bootstrap4.min.js' %}"></script>

    <script type="text/javascript">
        $(document).ready(function() {
            $('#iddatatable').DataTable({
                "language": {
                            "url": "//cdn.datatables.net/plug-ins/1.10.18/i18n/Spanish.json"
                        },
                "order": [[ 3, "desc" ]]    // Ordenamos por la fecha de creación
            });
        } );
    </script>
{% endblock extrascripts %}

uvmadmin_v4/noticias/templates/noticias/noticia_update_form.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}Editar noticia{% endblock title %}

{% block libreriasCSS %}
{% endblock libreriasCSS %}

{% block content %}

    <!-- BREADCRUMB -->
    <div class="row">
        <div class="col-xl-12">
            <div class="breadcrumb-holder">
                <h1 class="main-title float-left">Noticias</h1>
                <ol class="breadcrumb float-right">
                    <li class="breadcrumb-item">Inicio</li>
                    <li class="breadcrumb-item">Noticias</li>
                    <li class="breadcrumb-item active">Editar</li>
                </ol>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>

    <!-- PANEL DE LA NOTICIA -->
    <div class="card">

      <!-- MENÚ DE NOTICIAS -->
      <h5 class="card-header text-white bg-dark">  
        {% if request.user.is_active %}
          {% include 'noticias/includes/_menu.html'%}
        {% endif %}
      </h5>

      <!-- DETALLE DE LA NOTICIA --> 
      <div class="card-body">
          <h5 class="card-title"></h5>
          <!-- Si se ha editado correctamente muestra mensaje y enlace al detalle de la noticia -->
          {% if 'ok' in request.GET %}
            <p class="card-text" style="color:green;">
              Noticia editada correctamente. 
              <a href="{% url 'noticias:noticia' noticia.id noticia.title|slugify %}">Haz clic aquí para ver el resultado</a>.
            </p>
          {% endif %}

          <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
              <div class="row mt-3">
                <!-- IMÁGEN Y BOTONES DEL FORMULARIO -->
                <div class="col-md-2">
                  <div class="row">
                    <input type="submit" class="btn btn-primary btn-block" value="Actualizar" />
                  </div>
                  <div class="row mt-2">
                    <a class="btn btn-secondary btn-block" href="{% url 'noticias:noticias' %}">Cancelar</a>
                  </div>
                </div>

                <!-- DETALLE DE LA NOTICIA -->
                <div class="col-md-10"> 
                    <!-- TABS. Editar noticia y Galería de Fotos -->
                    <ul class="nav nav-tabs" id="myTab" role="tablist">
                        <li class="nav-item">
                          <a class="nav-link active" data-toggle="tab" href="#tabDetalle" role="tab" aria-controls="home" aria-selected="true">
                            DETALLE
                          </a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" id="profile-tab" data-toggle="tab" href="#tabPortada" role="tab" aria-controls="profile" aria-selected="false">
                            IMAGEN
                          </a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" id="profile-tab" data-toggle="tab" href="#tabGaleria" role="tab" aria-controls="profile" aria-selected="false">
                            GALERÍA
                          </a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" id="profile-tab" data-toggle="tab" href="#tabFicheros" role="tab" aria-controls="profile" aria-selected="false">
                            FICHERO ADJUNTO
                          </a>
                        </li>
                    </ul>

                    <!-- Contenido de los TABS -->
                    <div class="tab-content" id="myTabContent">                
                        
                        <!-- Detalle de la Noticia -->
                        <div class="tab-pane fade show active" id="tabDetalle" role="tabpanel">
                              <div class="row mt-3 ml-3">
                                <!-- Datos de la noticia -->
                                <div class="col-md-12">                                      
                                  <input type="hidden" id="{{form.author.name}}" name="{{form.author.name}}" value="{{request.user.id}}">             
                                  <!-- Título de la noticia -->
                                  {{ form.title }}

                                  <!-- Entradilla de la noticia -->
                                  {{ form.subject }}

                                  <!-- Contenido (Editor de Texto) -->
                                  {{ form.content }}       

                                  <!-- Fecha de Publicación -->      
                                  <p><b>Fecha de Publicación</b></p>
                                  {{ form.published }}

                                </div>              
                              </div>
                        </div>

                        <!-- Foto de Portada -->
                        <div class="tab-pane fade" id="tabPortada" role="tabpanel">
                            <div class="row mt-3 ml-3">
                              <!-- Imagen de la noticia -->                      
                              <div class="custom-file">                      
                                <input type="file" class="custom-file-input mb-2" accept=".jpg,.gif,.png" 
                                        id="{{form.image.name}}" name="{{form.image.name}}">
                                <label class="custom-file-label" for="{{form.image.name}}">Seleccione Imágen de portada...</label>
                              </div>
                              {% if form.image.value %}
                                <img src="{{form.image.value.url}}" class="img-fluid mt-2" style="max-height: 50%; max-width: 50%;">                  
                                <p class="mt-1">¿Borrar? <input type="checkbox" id="image-clear_id" name="image-clear" /></p>
                              {% else %}
                                <img src="{% static 'noticias/img/no-image.png' %}" class="img-fluid mt-2">
                              {% endif %}
                            </div>
                        </div>

                        <!-- Galería de Fotos -->
                        <div class="tab-pane fade" id="tabGaleria" role="tabpanel">

                          <!-- Selección de la Galería de Fotos -->  
                          <div class="row mt-3 ml-3">
                            {{ form.galeria }}  
                          </div>
                        
                          {% if noticia.galeria %}
                            <div class="row mt-3 ml-3 mb-3">
                              <a href="{% url 'gallery:album_update' noticia.galeria.id %}" 
                                  id="mod_galeria" name="mod_galeria" class="btn btn-secondary btn-block">Añadir Imágenes</a>
                            </div>
                          {% else %}
                            <div class="row mt-3 ml-3">
                              <div class="form-row">
                                <a class="btn btn-secondary" href="{% url 'gallery:album_create' %}" role="button">Añádir Nueva Galería</a>                    
                              </div>
                            </div>
                            <!-- Botón que llama al formulario modal -->                      
                            <button type="button" class="add-galeria btn btn-primary" data-id="{% url 'gallery:album_create' %}">
                                Añadir Nueva Galería <span class="fas fa-plus-circle"></span>
                            </button>                 
                          {% endif %}

                          {% if noticia.galeria %}
                            <div class="card-columns mt-3 ml-3">
                                {% for imagen in noticia.galeria.images.all %}
                                    <div class="card">
                                      <img class="card-img-top" src="{{imagen.data.url}}">
                                    </div>
                                {% endfor %}
                            </div>
                          {% endif %}

                        </div>

                        <!-- Ficheros adjuntos (Por ahora solo uno) -->
                        <div class="tab-pane fade" id="tabFicheros" role="tabpanel">

                          <!-- Selección del fichero adjunto -->
                          <div class="custom-file mt-3 ml-3">

                            <input type="file" class="custom-file-input" accept=".pdf" 
                                    id="{{form.fichero.name}}" name="{{form.fichero.name}}" placeholder="{{form.fichero.value}}">
                            
                            {% if form.fichero.value %}
                              <label class="custom-file-label" for="{{form.fichero.name}}">{{form.fichero.value}}</label>
                              <p class="mt-1">Eliminar <input type="checkbox" id="fichero-clear_id" name="fichero-clear" /></p>
                            {% else %}
                              <label class="custom-file-label" for="{{form.fichero.name}}">Seleccione fichero adjunto...</label>
                            {% endif %}                         

                          </div>  
                        </div>                      
                    </div>

                </div>        
        </form>

      </div>
    </div>
  
{% endblock content %} 


{% block extrascripts %} 

    <script>
      // Add the following code if you want the name of the file appear on select
      $(".custom-file-input").on("change", function() {
        var fileName = $(this).val().split("\\").pop();
        $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
      });
    </script>


{% endblock extrascripts %}