uvmadmin_v4/core/urls.py
from django.urls import path
from .views import home

core_patterns = ([
    path('', home.as_view(), name='home'),  
], 'core')

uvmadmin_v4/gallery/urls.py
from django.urls import path

from gallery.views import (AlbumView, AlbumList, 
                           AlbumCreate, AlbumDelete, AlbumUpdate)

app_name = 'gallery'
urlpatterns = [
    path('', AlbumList.as_view(), name='album_list'),
    path('album/<int:pk>/<slug>/', AlbumView.as_view(), name='album_detail'),
    path('borrar/<int:pk>/', AlbumDelete.as_view(), name='album_delete'),
    path('crear/', AlbumCreate.as_view(), name='album_create'),
    path('editar/<int:pk>/', AlbumUpdate.as_view(), name='album_update'),
]

uvmadmin_v4/uvmadmin/urls.py
from django.contrib import admin
from django.urls import path, include
# URLs de las App Propias
from core.urls import core_patterns       
from noticias.urls import noticias_patterns     
from alumnos.urls import alumnos_patterns  
from ponentes.urls import ponentes_patterns
from materias.urls import materias_patterns
from matriculas.urls import matriculas_patterns
from pages.urls import pages_patterns
from universidad.urls import universidad_patterns
      
# Para poder ver imágenes en desarrollo (fichero static). Ver abajo del todo
from django.conf import settings

urlpatterns = [
    # Paths de las App propias
    path('', include(core_patterns)),
    path('noticias/', include(noticias_patterns)),
    path('alumnos/', include(alumnos_patterns)),
    path('materias/', include(materias_patterns)),
    path('ponentes/', include(ponentes_patterns)),
    path('matriculas/', include(matriculas_patterns)),
    path('paginas/', include(pages_patterns)),
    path('universidad/', include(universidad_patterns)),
    # Paths de terceros
    path('galeria/', include('gallery.urls')),
    # Paths del admin
    path('admin/', admin.site.urls),
    # Paths de Auth (Autenticación)
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('registration.urls')),        # Aumentamos las listas de posibles paths de accounts
]

# Para poder ver imágenes en desarrollo (fichero static)
if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

uvmadmin_v4/core/models.py
from django.db import models
from django.utils.timezone import now           # Para acceder a la fecha/hora actual

# ------------------------------------------------------------------------
#  Modelo: Edicion
#  Descripción: Ediciones de la Universidad de Verano de Maspalomas
# ------------------------------------------------------------------------
class Edicion(models.Model):
    des_edicion = models.CharField(max_length=100, verbose_name="Descripción")
    edicion = models.SmallIntegerField(default=0, verbose_name="Año Edición")
    activa = models.BooleanField(default=False, verbose_name="Edición Activa")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edición")

    class Meta:
        verbose_name = "edicion"
        verbose_name_plural = "ediciones"
        ordering = ['-created']

    def __str__(self):
        return self.des_edicion

uvmadmin_v4/core/views.py
# Para manejar las vistas genéricas de Django
from django.views.generic.base import TemplateView

# Para controlar el acceso de usuarios a las vistas
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

#============= Página Principal 'Home' ==============#
@method_decorator(login_required, name='dispatch')
class home(TemplateView):
    template_name = "core/home.html"

uvmadmin_v4/core/templates/core/base.html
{% load static from staticfiles %}      <!--  Cargamos los ficheros estáticos -->
{% load core_tags %}                    <!-- Cargamos los templatetags de core -->

<!DOCTYPE html>
<html lang="en">
<head> 
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="description" content="Universidad de Verano | Panel Admin">
    <meta name="author" content="AytoSBT - https://www.maspalomas.com">
    
    <!-- Incluímos el título base -->
    <title>{% block title %}{% endblock %} | UVM Administración</title> 

	<!-- Favicon -->
    <link rel="shortcut icon" href="assets/images/favicon.ico">    

    <!-- Librerías CSS Generales a todas las páginas - Dirigimos hacia la ruta de ficheros estáticos  -->
    <link rel="stylesheet" href="{% static 'core/terceros/bootstrap/bootstrap.min.css' %}"> 
    <link rel="stylesheet" href="{% static 'core/terceros/fontawesome/css/all.min.css' %}">   
    <link rel="stylesheet" href="{% static 'core/css/uvmadmin.css' %}">  

    {% block libreriasCSS %}{% endblock %}  <!-- Librerías CSS - Específicas -->
    {% block libreriasJS %}{% endblock %}  <!-- Librerías JS - Específicas -->
    {% block header %}{% endblock %}        <!-- Bloque Cabecera -->


</head>

<body class="adminbody">

    <div id="main">

        <!-- HEADER. Contendrá la cabecera del sitio, con su nombre y menú superior -->
        <div class="headerbar">

            <!-- LOGO -->
            <div class="headerbar-left">
                <a href="{% url 'core:home' %}" class="logo">
                    <img alt="Logo" src="{% static 'core/img/UVM_logo.jpg' %}" /> 
                    <span>AdminUVM</span>
                </a>
            </div>
    
            <nav class="navbar-custom">
    
                <ul class="list-inline float-right mb-0">
                    <!-- Ayuda y Soporte -->
                    <li class="list-inline-item dropdown notif">
                        <a class="nav-link dropdown-toggle arrow-none" data-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false">
                            <i class="fa fa-fw fa-question-circle"></i>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right dropdown-arrow dropdown-arrow-success dropdown-lg">
                            <!-- item-->
                            <div class="dropdown-item noti-title">
                                <h5><small>Ayuda y Soporte</small></h5>
                            </div>

                            <!-- item-->
                            <a target="_blank" href="https://www.maspalomas.com" class="dropdown-item notify-item">                                    
                                <p class="notify-details ml-0">
                                    <b>¿Tienes algún problema técnico, mejora, duda?</b>
                                    <span>Contacta con Nosotros</span>
                                </p>
                            </a>                              

                            <!-- All-->
                            <a title="Click para enviarnos un correo" target="_blank" href="https://www.maspalomas.com" class="dropdown-item notify-item notify-all">
                                <i class="fa fa-link"></i> Escríbenos un correo
                            </a>

                        </div>
                    </li>

                    <!-- Usuario (foto, perfil, nuevo usuario, salir -->
                    {% if request.user.is_authenticated %}                                
                        <li class="list-inline-item dropdown notif">
                            <!-- Imagen -->
                            <a class="nav-link dropdown-toggle nav-user" data-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false">
                                {% if request.user.profile.avatar %}
                                    <img src="{{request.user.profile.avatar.url}}" alt="Imágen Perfil" class="avatar-rounded">
                                {% else %}
                                    <img src="{% static 'core/img/usuario.svg' %}" alt="Imágen Perfil" class="avatar-rounded">
                                {% endif %}
                            </a>
                            <div class="dropdown-menu dropdown-menu-right profile-dropdown ">               

                                <!-- Menú del usuario -->
                                <div class="dropdown-item noti-title">
                                    {% if request.user.first_name %}
                                        <h5 class="text-overflow"><small>Hola, {{request.user.first_name}}</h5>
                                    {% else %}
                                        <h5 class="text-overflow"><small>Hola, {{request.user.username}}</h5>
                                    {% endif %}   
                                </div>

                                <!-- Perfil del usuario-->
                                <a href="{% url 'profile' %}" class="dropdown-item notify-item">
                                    <i class="fas fa-user-edit"></i> <span>Perfil</span>
                                </a>

                                <!-- Cerrar sesión del usuario-->
                                <a href="{% url 'logout' %}" class="dropdown-item notify-item">
                                    <i class="fas fa-sign-out-alt"></i> <span>Desconectar</span>
                                </a>

                                <!-- Si está autenticado añade "Nuevo Usuario" -->                                            
                                {% if request.user.is_staff %} 
                                    <a href="{% url 'signup' %}" class="dropdown-item notify-item">
                                        <i class="fas fa-user-plus"></i> <span>Nuevo Usuario</span>
                                    </a>
                                {% endif %}

                                <!-- item-->
                                <a target="_blank" href="https://www.universidadveranomaspalomas.org/" class="dropdown-item notify-item">
                                    <i class="fa fa-external-link"></i> <span>UVM</span>
                                </a>
                            </div>
                        </li>
                    {% else %}   
                        <!-- Si no hay usuario activo, le invita a acceder -->
                        <li class="list-inline-item dropdown notif">
                            <a class="nav-link" href="{% url 'login' %}" role="button" aria-haspopup="false" aria-expanded="false">
                                <i class="fa fa-fw fa-user-plus"></i> Acceder
                            </a>
                        </li>
                    {% endif %}

                </ul> 

                <ul class="list-inline menu-left mb-0">
                    <li class="float-left">
                        <button class="button-menu-mobile open-left">
                            <i class="fa fa-fw fa-bars"></i>
                        </button>
                    </li>                        
                </ul>
    
            </nav>
        
        </div>
        <!-- End Navigation -->

	    <!-- Left Sidebar -->
        {% if request.user.is_authenticated %}
            <div class="left main-sidebar">
        
                <div class="sidebar-inner leftscroll">
        
                    <div id="sidebar-menu">
                
                        <ul>
                            <!-- Panel de Control -->
                            <li class="submenu">
                                <a class="active" href="{% url 'core:home' %}"><i class="fa fa-fw fa-bars"></i>
                                <span> Panel de Control </span> </a>
                            </li>

                            <!-- Alumnos -->
                            <li class="submenu">
                                <a href="{% url 'alumnos:alumnos' %}">
                                    <i class="fas fa-fw fa-graduation-cap"></i><span> Alumnos </span>
                                    <span class="label radius-circle bg-primary float-right">{% get_alumnos_count %}</span>
                                </a>
                            </li>

                            <!-- Ponentes -->
                            <li class="submenu">
                                <a href="{% url 'ponentes:ponentes' %}">
                                    <i class="fas fa-fw fa-chalkboard-teacher"></i><span> Ponentes </span>
                                    <span class="label radius-circle bg-warning float-right">{% get_ponentes_count %}</span>
                                </a>
                            </li>                        

                            <!-- Materias -->
                            <li class="submenu">
                                <a href="{% url 'materias:materias' %}">
                                    <i class="fas fa-fw fa-book"></i><span> Materias </span>
                                    <span class="label radius-circle bg-danger float-right">{% get_materias_count %}</span>
                                </a>
                            </li>

                            <!-- Matrículas -->
                            <li class="submenu">
                                <a href="{% url 'matriculas:matriculas' %}">
                                    <i class="fas fa-fw fa-id-card"></i><span> Matrículas </span>
                                    <span class="label radius-circle bg-info float-right">{% get_matriculas_count %}</span>
                                </a>
                            </li>                        

                            <!-- Noticias -->
                            <li class="submenu">
                                <a href="{% url 'noticias:noticias' %}">
                                    <i class="fas fa-fw fa-newspaper"></i><span> Noticias </span>
                                    <span class="label radius-circle bg-success float-right">{% get_noticias_count %}</span>
                                </a>
                            </li> 

                            <!-- Galería -->
                            <li class="submenu">
                                <a href="{% url 'gallery:album_list' %}">
                                    <i class="fas fa-fw fa-images"></i><span> Galería </span>     
                                    <span class="label radius-circle bg-secondary float-right">{% get_galerias_count %}</span>
                                                               
                                </a>
                            </li>

                        </ul>
        
                        <div class="clearfix"></div>
        
                    </div>
                
                    <div class="clearfix"></div>
        
                </div>
        
            </div>
        {% endif %}
        <!-- End Sidebar -->

        <!-- Contenedor de las páginas -->
        <div class="content-page">	
        
            <!-- Contenido de las páginas -->
            <div class="content">        
                {% block content %}                    
                    {% block estadisticas %}{% endblock %}      <!-- Solo aparece en la página principal -->
                {% endblock %}
            </div>

        </div>

        <!-- Pié de página -->
        <footer class="footer">
            <span class="text-right">
                Copyright <a target="_blank" href="https://www.maspalomas.com">Ayuntamiento de San Bartolomé de Tirajana</a>
            </span>
            <span class="float-right">
                Powered by <a target="_blank" href="{% url 'core:home' %}"><b>Departamento Nuevas Tecnologías</b></a>
            </span>
        </footer>

    </div>

    
    <!-- Librerías JS - Generales -->
    <script src="{% static 'core/terceros/jquery/modernizr.min.js' %}"></script>
    <script src="{% static 'core/terceros/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'core/terceros/jquery/moment.min.js' %}"></script>
            
    <script src="{% static 'core/terceros/jquery/popper.min.js' %}"></script>
    <script src="{% static 'core/terceros/bootstrap/bootstrap.min.js' %}"></script>
    
    <script src="{% static 'core/terceros/jquery/detect.js' %}"></script>       <!-- Controla la redimensión menú lateral -->
    <script src="{% static 'core/terceros/jquery/fastclick.js' %}"></script>    <!-- Controla el contador -->
    <script src="{% static 'core/terceros/jquery/jquery.blockUI.js' %}"></script>
    <script src="{% static 'core/terceros/jquery/jquery.nicescroll.js' %}"></script>    

    <script src="{% static 'core/js/uvmadmin.js' %}"></script>

    {% block extrascripts %}{% endblock extrascripts %}  

</body>

</html>

uvmadmin_v4/core/templates/core/home.html
{% extends 'core/base.html' %}          <!-- Cargamos el código html común -->
{% load static %}                       <!-- Cargamos los ficheros estáticos -->
{% load core_tags %}                    <!-- Cargamos los templatetags de core -->

{% block title %}Inicio{% endblock %}   <!-- Título de la página -->
 
{% block libreriasCSS %}{% endblock libreriasCSS %}

{% block content %}

    <!-- BREADCRUMB -->
    <div class="row">
        <div class="col-xl-12">
            <div class="breadcrumb-holder">
                <h1 class="main-title float-left">Panel de Control</h1>
                <ol class="breadcrumb float-right">
                    <li class="breadcrumb-item">Inicio</li>
                    <li class="breadcrumb-item active">Panel de Control</li>
                </ol>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>

    <!-- MANTENIMIENTOS ALUMNOS, PONENTES, MATERÍAS Y MATRÍCULAS -->
    <div class="row">
        <!-- Alumnos -->
        <div class="col-xs-12 col-md-6 col-lg-6 col-xl-3">
            <div class="card-box noradius noborder bg-default">
                <i class="fas fa-id-card float-right text-white"></i>
                <a href="{% url 'alumnos:alumnos' %}">
                    <h6 class="text-white text-uppercase m-b-20">Alumnos</h6>
                </a>
                <h1 class="m-b-20 text-white counter">{% get_alumnos_count %}</h1>
                <span class="text-white">15 Nuevos Alumnos</span>
            </div>
        </div>

        <!-- Ponentes -->
        <div class="col-xs-12 col-md-6 col-lg-6 col-xl-3">
            <div class="card-box noradius noborder bg-warning">
                <i class="fas fa-chalkboard-teacher float-right text-white"></i>
                <a href="{% url 'ponentes:ponentes' %}">
                    <h6 class="text-white text-uppercase m-b-20">Ponentes</h6>
                </a>
                <h1 class="m-b-20 text-white counter">{% get_ponentes_count %}</h1>
                <span class="text-white">3 Nuevos Ponentes</span>
            </div>
        </div>

        <!-- Materias -->
        <div class="col-xs-12 col-md-6 col-lg-6 col-xl-3">
            <div class="card-box noradius noborder bg-danger">
                <i class="fas fa-book float-right text-white"></i>
                <a href="{% url 'materias:materias' %}">
                    <h6 class="text-white text-uppercase m-b-20">Materias</h6>
                </a>
                <h1 class="m-b-20 text-white counter">{% get_materias_count %}</h1>
                <span class="text-white">5 Nuevas Materias</span>
            </div>
        </div>

        <!-- Matrículas -->
        <div class="col-xs-12 col-md-6 col-lg-6 col-xl-3">
            <div class="card-box noradius noborder bg-info">
                <i class="fas fa-id-card float-right text-white"></i>
                <a href="{% url 'matriculas:matriculas' %}">
                    <h6 class="text-white text-uppercase m-b-20">Matrículas</h6>
                </a>
                <h1 class="m-b-20 text-white counter">{% get_matriculas_count %}</h1>
                <span class="text-white">25 Nuevas Matrículas</span>
            </div>
        </div>

    </div>

    <!-- NOTICIAS, INFORMACIÓN, UNIVERSIDAD Y GALERÍA -->
    <div class="row">
        <div class="col-xs-12 col-md-6 col-lg-6 col-xl-3">
            <div class="card-box noradius noborder bg-success">
                <i class="fas fa-newspaper float-right text-white"></i>
                <a href="{% url 'noticias:noticias' %}">
                    <h6 class="text-white text-uppercase m-b-20">Noticias</h6>
                </a>
                <h1 class="m-b-20 text-white counter">{% get_noticias_count %}</h1>
                <span class="text-white">2 Nuevas Noticias</span>
            </div>
        </div>

        <div class="col-xs-12 col-md-6 col-lg-6 col-xl-3">
            <div class="card-box noradius noborder bg-primary">
                <i class="fas fa-info-circle float-right text-white"></i>
                <a href="{% url 'pages:pages' %}">
                    <h6 class="text-white text-uppercase m-b-20">Información</h6>
                </a>
                <p class="m-b-20 text-white">Proceso de matrícula, fechas, precios, condiciones, transporte, alojamiento...</p>
            </div>
        </div>

        <div class="col-xs-12 col-md-6 col-lg-6 col-xl-3">
            <div class="card-box noradius noborder bg-brown">
                <i class="fas fa-university float-right text-white"></i>
                <a href="{% url 'universidad:organizadores' %}">
                    <h6 class="text-white text-uppercase m-b-20">La Universidad</h6>
                </a>
                <p class="m-b-20 text-white">Patrocinadores, Colaboradores, Organizadores.</p>
            </div>
        </div>

        <div class="col-xs-12 col-md-6 col-lg-6 col-xl-3">
            <div class="card-box noradius noborder bg-secondary-dark">
                <i class="fas fa-images float-right text-white"></i>
                <a href="{% url 'gallery:album_list' %}">
                    <h6 class="text-white text-uppercase m-b-20">Galería</h6>
                </a>
                <p class="m-b-20 text-white">Álbumes de fotos utilizadas en las noticias</p>
                <span class="text-white">8 Álbumes</span>
            </div>
        </div>

    </div>


{% endblock content %}


{% block extrascripts %}    

    <!-- Counter-Up-->    
    <script src="{% static 'core/terceros/jquery/waypoints/lib/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'core/terceros/jquery/counterup/jquery.counterup.min.js' %}"></script>			

    <script>
        $(document).ready(function() {
            // counter-up
            $('.counter').counterUp({
                delay: 10,
                time: 600
            });
        } );		
    </script>

{% endblock extrascripts %}